from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Attachment, FileContent, FileName, FileType, Disposition
from ..core.config import settings
import base64
from typing import Optional


class EmailService:
    def __init__(self):
        self.sg = SendGridAPIClient(api_key=settings.SENDGRID_API_KEY)
        self.from_email = settings.FROM_EMAIL
    
    async def send_alert_email(
        self,
        to_email: str,
        user_name: str,
        aoi_name: str,
        alert_type: str,
        confidence: float,
        gif_data: Optional[str] = None,
        alert_url: Optional[str] = None
    ):
        """Send environmental alert email"""
        
        subject = f"🚨 Environmental Alert: {alert_type.replace('_', ' ').title()} detected in {aoi_name}"
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>GeoGuardian Alert</title>
        </head>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
                <h1 style="color: white; margin: 0; font-size: 28px;">🌍 GeoGuardian Alert</h1>
                <p style="color: #f0f0f0; margin: 10px 0 0 0; font-size: 16px;">Environmental Monitoring System</p>
            </div>
            
            <div style="background: white; padding: 30px; border: 1px solid #e0e0e0; border-top: none;">
                <h2 style="color: #333; margin-top: 0;">Hello {user_name},</h2>
                
                <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
                    <h3 style="margin-top: 0; color: #e74c3c;">🚨 Alert Details</h3>
                    <p><strong>Location:</strong> {aoi_name}</p>
                    <p><strong>Type:</strong> {alert_type.replace('_', ' ').title()}</p>
                    <p><strong>Confidence:</strong> {confidence:.1%}</p>
                    <p><strong>Detection Time:</strong> Just now</p>
                </div>
                
                <p>Our satellite monitoring system has detected a significant environmental change in your Area of Interest: <strong>{aoi_name}</strong>.</p>
                
                <p>The system identified this change as: <strong>{alert_type.replace('_', ' ').title()}</strong> with {confidence:.1%} confidence.</p>
                
                {f'<div style="text-align: center; margin: 30px 0;"><img src="{gif_data}" alt="Before/After Comparison" style="max-width: 100%; height: auto; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.15);"></div>' if gif_data else ''}
                
                <div style="text-align: center; margin: 30px 0;">
                    <a href="{alert_url or settings.FRONTEND_URL}" 
                       style="background: #667eea; color: white; padding: 15px 30px; text-decoration: none; border-radius: 25px; display: inline-block; font-weight: bold; transition: background 0.3s;">
                        View Full Alert Details
                    </a>
                </div>
                
                <div style="background: #fff3cd; border: 1px solid #ffeaa7; border-radius: 8px; padding: 15px; margin: 20px 0;">
                    <h4 style="margin-top: 0; color: #856404;">⚡ Help Us Verify</h4>
                    <p style="margin-bottom: 0; color: #856404;">Please review this alert and help our community verify its accuracy. Your feedback helps improve our detection system.</p>
                </div>
                
                <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 30px 0;">
                
                <p style="font-size: 14px; color: #666;">
                    This alert was generated by GeoGuardian's automated satellite monitoring system. 
                    The system analyzes Sentinel-2 satellite imagery to detect environmental changes.
                </p>
                
                <p style="font-size: 12px; color: #999; margin-top: 20px;">
                    To unsubscribe or modify your alert preferences, please visit your 
                    <a href="{settings.FRONTEND_URL}/settings" style="color: #667eea;">account settings</a>.
                </p>
            </div>
            
            <div style="background: #f8f9fa; padding: 20px; text-align: center; border-radius: 0 0 10px 10px; border: 1px solid #e0e0e0; border-top: none;">
                <p style="margin: 0; font-size: 14px; color: #666;">
                    © 2024 GeoGuardian - Democratizing Environmental Monitoring
                </p>
            </div>
        </body>
        </html>
        """
        
        message = Mail(
            from_email=self.from_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_content
        )
        
        try:
            response = self.sg.send(message)
            return response.status_code == 202
        except Exception as e:
            print(f"Error sending email: {e}")
            return False
    
    async def send_welcome_email(self, to_email: str, user_name: str):
        """Send welcome email to new users"""
        subject = "Welcome to GeoGuardian! 🌍"
        
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
                <h1 style="color: white; margin: 0;">🌍 Welcome to GeoGuardian!</h1>
            </div>
            
            <div style="background: white; padding: 30px; border: 1px solid #e0e0e0;">
                <h2>Hello {user_name}!</h2>
                
                <p>Welcome to GeoGuardian - your personal environmental monitoring system! 🎉</p>
                
                <p>You can now:</p>
                <ul>
                    <li>📍 Create up to 5 Areas of Interest anywhere on Earth</li>
                    <li>🛰️ Get automatic satellite monitoring alerts</li>
                    <li>📧 Receive instant email notifications of changes</li>
                    <li>👥 Help verify community alerts</li>
                </ul>
                
                <div style="text-align: center; margin: 30px 0;">
                    <a href="{settings.FRONTEND_URL}" 
                       style="background: #667eea; color: white; padding: 15px 30px; text-decoration: none; border-radius: 25px; display: inline-block; font-weight: bold;">
                        Start Monitoring
                    </a>
                </div>
                
                <p>Happy monitoring! 🚀</p>
                <p>The GeoGuardian Team</p>
            </div>
        </body>
        </html>
        """
        
        message = Mail(
            from_email=self.from_email,
            to_emails=to_email,
            subject=subject,
            html_content=html_content
        )
        
        try:
            response = self.sg.send(message)
            return response.status_code == 202
        except Exception as e:
            print(f"Error sending welcome email: {e}")
            return False


# Global instance
email_service = EmailService()
